"""
Django settings for magasin project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import ConfigParser as configparser
import logging

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/


#Import platform specific configuration
CONFIG = configparser.SafeConfigParser(allow_no_value=True)
CONFIG.read(os.environ.get('MAGASIN_INI', '/etc/magasin.ini'))

DEBUG = CONFIG.get('general', 'debug')
API_URL = CONFIG.get('general', 'api')
STATIC_URL = CONFIG.get('general', 'static_url')
STATIC_ROOT = CONFIG.get('general', 'static_root') or os.path.join(BASE_DIR, "static")

DATABASES = {
    'default': {
        'NAME': CONFIG.get('database', 'name'),
        'ENGINE': CONFIG.get('database', 'engine'),
        'USER': CONFIG.get('database', 'user'),
        'PASSWORD': CONFIG.get('database', 'password'),
        'HOST': CONFIG.get('database', 'host'),
        'PORT': CONFIG.get('database', 'port'),
    }
}

SECRET_KEY = CONFIG.get('security', 'secret_key')
ALLOWED_HOSTS = [CONFIG.get('security', 'allowed_host')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Third party packages
    'bootstrap3',
    #Magasin packages
    'magasin.apps.base',
    'magasin.apps.account',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'magasin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'magasin.apps.base.context_processors.is_connected',
            ],
        },
    },
]

WSGI_APPLICATION = 'magasin.wsgi.application'



# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
if DEBUG:
    logging.basicConfig(
        level=logging.DEBUG,
        format='%(asctime)s %(levelname)s %(message)s',
    )

AUTH_USER_MODEL = 'base.APIUser'
AUTHENTICATION_BACKENDS = ['magasin.utils.auth.APIAuthBackend']
LOGIN_URL = '/signin/'
